version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update
      - apt-get --assume-yes install google-chrome-stable
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
      - npm run lint
      - npm test -- --no-watch --no-progress --browsers=ChromeHeadless
  build:
    commands:
      - ng build --prod='true'
  post_build:
    commands:
      - mv appspec.yml dist/job-clouds-front/
      - tar -C dist/ -zcvf job-clouds-front.tar.gz job-clouds-front
artifacts:
  name: job-clouds-front
  files:
    - job-clouds-front.tar.gz
  discard-paths: yes
