version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update
      - apt-get --assume-yes install google-chrome-stable
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
      - npm run lint
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
  build:
    commands:
      - ng build --prod='true'
artifacts:
  files:
    - dist/**/*
    - appspec.yml
  discard-paths: yes
